/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;
import Controller.DAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.MatHang;
import javax.swing.JOptionPane;

/**
 *
 * @author ad
 */
public class DanhMucMH extends javax.swing.JFrame {
    
    private ArrayList<MatHang> listMatHang;
    DefaultTableModel model;
    private Socket socket = null;
    private PrintWriter out= null;
    private Scanner in = null;
    public DanhMucMH() {
        initComponents();
        model = (DefaultTableModel) tblMatHang.getModel();
        //this.setLocationRelativeTo(null);
        listMatHang = new DAO().getListMatHang();
        fillComboBox();
        showTable();
    }
    public void showTable() {
    if (model != null && listMatHang != null) {
        for (MatHang matHang : listMatHang) {
            
            model.addRow(new Object[]{
                i++, matHang.isDisable(), matHang.getMaLoai(), matHang.getMaMH(), matHang.getTenMH(), 
                matHang.getGiaBan(), matHang.getDVT(), matHang.getMoTa()
            });
        }
    } else {
        System.err.println("Model or listMatHang is null. Check initialization.");
    }
    }

    private void fillComboBox() {
        try {
            // Kết nối đến cơ sở dữ liệu (thay đổi thông tin kết nối tùy theo cấu hình của bạn)
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=VANPHONGPHAM;user=sa;password=huynhtanloc_0x");

            // Thực hiện truy vấn để lấy dữ liệu từ cơ sở dữ liệu
            
                String query = "SELECT * FROM LOAI_MAT_HANG";
            try (PreparedStatement statement = connection.prepareStatement(query);
                 ResultSet resultSet = statement.executeQuery()) {

                // Đổ dữ liệu vào ComboBox
                while (resultSet.next()) {
                    String item = resultSet.getString("MALOAI");
                    cmbMatHang.addItem(item);
                }
                
            }
            // dong ket noi
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Them = new javax.swing.JButton();
        Sua = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Thoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMatHang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbMatHang = new javax.swing.JComboBox<>();
        txtMaMH = new javax.swing.JTextField();
        txtMatHang = new javax.swing.JTextField();
        checkDisable = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        txtDVT = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Them.setText("Thêm");
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        Sua.setText("Sửa");
        Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaActionPerformed(evt);
            }
        });

        Xoa.setText("Xoá");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        jButton5.setText("Lưu");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("Bỏ qua");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Thoat.setText("Thoát");
        Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Them, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
            .addComponent(Sua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblMatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Disable", "NHÓM MẶT HÀNG", "MÃ MẶT HÀNG", "MẶT HÀNG", "GIÁ BÁN", "DVT", "MÔ TẢ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMatHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMatHang);
        if (tblMatHang.getColumnModel().getColumnCount() > 0) {
            tblMatHang.getColumnModel().getColumn(0).setMinWidth(50);
            tblMatHang.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblMatHang.getColumnModel().getColumn(0).setMaxWidth(100);
            tblMatHang.getColumnModel().getColumn(1).setMinWidth(50);
            tblMatHang.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblMatHang.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Thông tin mặt hàng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Loại mặt hàng ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Giá bán");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Mã mặt hàng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Mặt hàng");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("DVT");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Mô tả");

        cmbMatHang.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtMaMH.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtMatHang.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        checkDisable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        checkDisable.setText("Disable");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        txtDVT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbMatHang, 0, 145, Short.MAX_VALUE)
                            .addComponent(txtMaMH)
                            .addComponent(txtGia))))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(checkDisable))
                    .addComponent(txtMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(cmbMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(txtMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkDisable)
                            .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        // TODO add your handling code here:
        
        MatHang s = new MatHang();
            s.setMaLoai(cmbMatHang.getSelectedItem().toString());
            s.setMaMH(txtMaMH.getText());
            s.setTenMH(txtMatHang.getText());
            s.setGiaBan(Integer.parseInt(txtGia.getText()));
            s.setDVT(txtDVT.getText());
            s.setMoTa(txtMoTa.getText());
            s.setDisable(checkDisable.isSelected());
        
            if(new DAO().addMatHang(s)){
                JOptionPane.showMessageDialog(rootPane, "Add Success!");
                listMatHang.add(s); // them vao danh sach SV
            } else{
                JOptionPane.showMessageDialog(rootPane, "Mat hang cannot be duplicated!");
            }
            
            showResult();
    }//GEN-LAST:event_ThemActionPerformed
    
    
    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        // TODO add your handling code here:
        // Lấy mặt hàng được chọn từ danh sách
        int selectedIndex = tblMatHang.getSelectedRow();
        
        if (selectedIndex >= 0) {
        // Lấy mã mặt hàng từ dòng được chọn
            String maMH = tblMatHang.getValueAt(selectedIndex, 3).toString(); // Giả sử cột 3 là cột chứa MAMH
            model.removeRow(selectedIndex);
            
        // Xóa mặt hàng từ cơ sở dữ liệu
            if (new DAO().deleteMatHang(maMH)) {
            
                JOptionPane.showMessageDialog(rootPane, "Delete Success!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Delete Failed!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Select a row to delete!");
        }
    }//GEN-LAST:event_XoaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblMatHang.getSelectedRow();

    if (selectedIndex >= 0) {
        // Lấy thông tin mặt hàng từ form
        MatHang updatedMatHang = new MatHang();
        updatedMatHang.setMaLoai(cmbMatHang.getSelectedItem().toString());
        updatedMatHang.setMaMH(txtMaMH.getText());
        updatedMatHang.setTenMH(txtMatHang.getText());
        updatedMatHang.setGiaBan(Integer.parseInt(txtGia.getText()));
        updatedMatHang.setDVT(txtDVT.getText());
        updatedMatHang.setMoTa(txtMoTa.getText());
        updatedMatHang.setDisable(checkDisable.isSelected());

        // Lấy danh sách mặt hàng từ cơ sở dữ liệu
        ArrayList<MatHang> matHangList = new DAO().getListMatHang();
        // Cập nhật thông tin mặt hàng trong danh sách
        if (new DAO().updateListMatHangFromForm(updatedMatHang, matHangList)) {
            JOptionPane.showMessageDialog(rootPane, "Update Success!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Update Failed!");
        }
        updatedMatHang.setMaLoai(cmbMatHang.getSelectedItem().toString());
        updatedMatHang.setMaMH(txtMaMH.getText());
        updatedMatHang.setTenMH(txtMatHang.getText());
        updatedMatHang.setGiaBan(Integer.parseInt(txtGia.getText()));
        updatedMatHang.setDVT(txtDVT.getText());
        updatedMatHang.setMoTa(txtMoTa.getText());
        updatedMatHang.setDisable(checkDisable.isSelected());
        // Cập nhật lại hiển thị trên bảng
            if (selectedIndex != -1) {
            // Cập nhật giá trị trong model của JTable
            tblMatHang.setValueAt(checkDisable.isSelected(), selectedIndex, 1);
            tblMatHang.setValueAt(cmbMatHang.getSelectedItem().toString(), selectedIndex, 2);
            tblMatHang.setValueAt(txtMaMH.getText(), selectedIndex, 3);
            tblMatHang.setValueAt(txtMatHang.getText(), selectedIndex, 4);
            tblMatHang.setValueAt(txtGia.getText(), selectedIndex, 5);
            tblMatHang.setValueAt(txtDVT.getText(), selectedIndex, 6);
            tblMatHang.setValueAt(txtMoTa.getText(), selectedIndex, 7);
            
        } else {
            JOptionPane.showMessageDialog(this, "Select a row to edit.");
        }
    } else {
        JOptionPane.showMessageDialog(rootPane, "Select a row to update!");
    }
    }//GEN-LAST:event_SuaActionPerformed

    private void tblMatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMatHangMouseClicked
        // TODO add your handling code here:
        int viTriDongVuaBam = tblMatHang.getSelectedRow();
        checkDisable.setSelected((boolean)tblMatHang.getValueAt(viTriDongVuaBam, 1));
        cmbMatHang.setActionCommand(tblMatHang.getValueAt(viTriDongVuaBam, 3).toString());
        txtMaMH.setText(tblMatHang.getValueAt(viTriDongVuaBam, 3).toString());
        txtMatHang.setText(tblMatHang.getValueAt(viTriDongVuaBam, 4).toString());
        txtGia.setText(tblMatHang.getValueAt(viTriDongVuaBam, 5).toString());
        txtDVT.setText(tblMatHang.getValueAt(viTriDongVuaBam, 6).toString());
        txtMoTa.setText(tblMatHang.getValueAt(viTriDongVuaBam, 7).toString());
    }//GEN-LAST:event_tblMatHangMouseClicked

    private void ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatActionPerformed
        // TODO add your handling code here:
        this.hide();
//        frmHomePage frm= new frmHomePage();
//        frm.show();
    }//GEN-LAST:event_ThoatActionPerformed
    
    int i = 1;

    public void showResult() {
        MatHang s = listMatHang.get(listMatHang.size() - 1);
        model.addRow(new Object[]{
            i++, s.isDisable(), s.getMaLoai(), s.getMaMH(), s.getTenMH(), s.getGiaBan(), s.getDVT(), s.getMoTa()
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhMucMH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhMucMH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhMucMH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhMucMH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhMucMH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sua;
    private javax.swing.JButton Them;
    private javax.swing.JButton Thoat;
    private javax.swing.JButton Xoa;
    private javax.swing.JCheckBox checkDisable;
    private javax.swing.JComboBox<String> cmbMatHang;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMatHang;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaMH;
    private javax.swing.JTextField txtMatHang;
    private javax.swing.JTextArea txtMoTa;
    // End of variables declaration//GEN-END:variables
}
